### ISSUE TITLE
TracIn for gradient boosting

### ISSUE THREAD

**Issue by tfjgeorge** [Orange-OpenSource/mislabeled#9]
I don't think it behaves as expected: because of the @linear api, it does not compute the boosting gradient, but rather considers a linearized model using the tree kernel.

**Comment by tfjgeorge** [comment]
https://github.com/Orange-OpenSource/mislabeled/blob/1e0a2bcd4be2b27a7bdd010a56f811a6e96ef1ff/tests/test_detect.py#L158C1-L158C69

**Comment by pierrenodet** [comment]
the @linear call happens after the stagging, on each stage generated by the progressive ensemble, so as expected!
